### ISSUE TITLE
TODO board

### ISSUE THREAD

**Issue by daehwan2da** [TeamFILL-IN/server-renew#29]
### `phase1`
: 핵심 및 기본 기능 구현
**[milestone](https://github.com/TeamFILL-IN/server-renew/milestone/2)**

- [ ] Auth feature ([issue](https://github.com/TeamFILL-IN/server-renew/issues/17))
  - [x] kakao
    - [x] 로그인 및 fillin token 발급
    - [x] 회원가입 fillin token 발급
  - [ ] apple 
    - [ ] apple 인증 방식 확인 필요
    - [ ] 로그인 및 fillin token 발급
    - [ ] 회원가입 fillin token 발급
- [x] Studio feature ([issue](https://github.com/TeamFILL-IN/server-renew/issues/25))
  - [x] 전체 스튜디오 조회
  - [x] 스튜디오 상세 조회
  - [x] 스튜디오 검색
- [ ] Gallery feature ([issue](https://github.com/TeamFILL-IN/server-renew/issues/31))
- [ ] User feature

### `phase2`
: phase1 구현 보완 및 추가 기능 구현
**[milestone](https://github.com/TeamFILL-IN/server-renew/milestone/3)**

- [ ] Studio
  - [ ] Bookmark 기능
